// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ads/google/callback': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/google/callback').default>>>>
    }
    '/api/ads/google/campaigns': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/google/campaigns').default>>>>
    }
    '/api/ads/google/connect': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/google/connect').default>>>>
    }
    '/api/ads/google/process': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/google/process/index.post').default>>>>
    }
    '/api/ads/google/report': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/google/report/index').default>>>>
    }
    '/api/ads/google/status': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/google/status').default>>>>
    }
    '/api/auth/callback/facebook': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/callback/facebook').default>>>>
    }
    '/api/auth/callback/google': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/callback/google').default>>>>
    }
    '/api/auth/callback/linkedin': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/callback/linkedin').default>>>>
    }
    '/api/auth/forgot-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/forgot-password.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/login/facebook': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login/facebook').default>>>>
    }
    '/api/auth/login/google': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login/google').default>>>>
    }
    '/api/auth/login/linkedin': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login/linkedin').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/reset-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset-password').default>>>>
    }
    '/api/teste/applicationOn': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teste/applicationOn').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_content/query/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/cache.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/cache').default>>>>
    }
    '/api/_content/navigation/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
  }
}
export {}