
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'WhatsAppChatHeader': typeof import("../components/WhatsApp/ChatHeader.vue")['default']
    'WhatsAppChatMessages': typeof import("../components/WhatsApp/ChatMessages.vue")['default']
    'WhatsAppContactCard': typeof import("../components/WhatsApp/ContactCard.vue")['default']
    'WhatsAppMessageInput': typeof import("../components/WhatsApp/MessageInput.vue")['default']
    'WhatsAppSidebar': typeof import("../components/WhatsApp/Sidebar.vue")['default']
    'EffectsCardHoverBorder': typeof import("../components/effects/CardHoverBorder.vue")['default']
    'EffectsCardHoverGlow': typeof import("../components/effects/CardHoverGlow.vue")['default']
    'EffectsNumberRotate': typeof import("../components/effects/NumberRotate.vue")['default']
    'EffectsScrollX': typeof import("../components/effects/ScrollX.vue")['default']
    'EffectsWriter': typeof import("../components/effects/Writer.vue")['default']
    'ElementsFooter': typeof import("../components/elements/Footer.vue")['default']
    'ElementsHeader': typeof import("../components/elements/Header.vue")['default']
    'ElementsLoading': typeof import("../components/elements/Loading.vue")['default']
    'ElementsModal': typeof import("../components/elements/Modal.vue")['default']
    'ElementsNavDashboard': typeof import("../components/elements/NavDashboard.vue")['default']
    'ElementsSteps': typeof import("../components/elements/Steps.vue")['default']
    'ElementsWhatsApp': typeof import("../components/elements/WhatsApp.vue")['default']
    'FieldButton': typeof import("../components/field/Button.vue")['default']
    'FieldInput': typeof import("../components/field/Input.vue")['default']
    'FieldSelect': typeof import("../components/field/Select.vue")['default']
    'FieldSocialButton': typeof import("../components/field/SocialButton.vue")['default']
    'FormsAuth': typeof import("../components/forms/Auth.vue")['default']
    'FormsNewPassword': typeof import("../components/forms/NewPassword.vue")['default']
    'FormsResetPassword': typeof import("../components/forms/ResetPassword.vue")['default']
    'IconsClose': typeof import("../components/icons/Close.vue")['default']
    'IconsHamburguer': typeof import("../components/icons/Hamburguer.vue")['default']
    'IconsLoading': typeof import("../components/icons/Loading.vue")['default']
    'IconsModal': typeof import("../components/icons/Modal.vue")['default']
    'IconsSocialIcon': typeof import("../components/icons/SocialIcon.vue")['default']
    'LogosBrand': typeof import("../components/logos/Brand.vue")['default']
    'SectionAdsReportsGoogle': typeof import("../components/section/AdsReports/Google.vue")['default']
    'SectionAdsReportsMeta': typeof import("../components/section/AdsReports/Meta.vue")['default']
    'SectionExpertises': typeof import("../components/section/Expertises.vue")['default']
    'SectionFormsBriefing': typeof import("../components/section/Forms/Briefing.vue")['default']
    'SectionFormsDados': typeof import("../components/section/Forms/Dados.vue")['default']
    'SectionHero': typeof import("../components/section/Hero.vue")['default']
    'SectionOurServicesAds': typeof import("../components/section/OurServices/Ads.vue")['default']
    'SectionOurServicesDesign': typeof import("../components/section/OurServices/Design.vue")['default']
    'SectionOurServicesSeo': typeof import("../components/section/OurServices/Seo.vue")['default']
    'SectionOurServicesSites': typeof import("../components/section/OurServices/Sites.vue")['default']
    'SectionPrices': typeof import("../components/section/Prices.vue")['default']
    'SectionProblemCases': typeof import("../components/section/ProblemCases.vue")['default']
    'SectionPropostaFunil': typeof import("../components/section/Proposta/Funil.vue")['default']
    'SectionPropostaFunil01': typeof import("../components/section/Proposta/Funil01.vue")['default']
    'SectionPropostaQuemSomos': typeof import("../components/section/Proposta/QuemSomos.vue")['default']
    'SectionProposta': typeof import("../components/section/Proposta/index.vue")['default']
    'SectionServices': typeof import("../components/section/Services.vue")['default']
    'SectionWhoUs': typeof import("../components/section/WhoUs.vue")['default']
    'ContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'ContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'ContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'ContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'ContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'ContentRendererMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'ContentSlot': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'DocumentDrivenEmpty': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'DocumentDrivenNotFound': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'Markdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'ProseCode': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
    'ProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'ProsePre': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'ProseA': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
    'ProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'ProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'ProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'ProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'ProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'ProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'ProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'ProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'ProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'ProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'ProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'ProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'ProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'ProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'ProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'ProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'ProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'ProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'ProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'ProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'ProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'ProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'MDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'MDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'MDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyWhatsAppChatHeader': typeof import("../components/WhatsApp/ChatHeader.vue")['default']
    'LazyWhatsAppChatMessages': typeof import("../components/WhatsApp/ChatMessages.vue")['default']
    'LazyWhatsAppContactCard': typeof import("../components/WhatsApp/ContactCard.vue")['default']
    'LazyWhatsAppMessageInput': typeof import("../components/WhatsApp/MessageInput.vue")['default']
    'LazyWhatsAppSidebar': typeof import("../components/WhatsApp/Sidebar.vue")['default']
    'LazyEffectsCardHoverBorder': typeof import("../components/effects/CardHoverBorder.vue")['default']
    'LazyEffectsCardHoverGlow': typeof import("../components/effects/CardHoverGlow.vue")['default']
    'LazyEffectsNumberRotate': typeof import("../components/effects/NumberRotate.vue")['default']
    'LazyEffectsScrollX': typeof import("../components/effects/ScrollX.vue")['default']
    'LazyEffectsWriter': typeof import("../components/effects/Writer.vue")['default']
    'LazyElementsFooter': typeof import("../components/elements/Footer.vue")['default']
    'LazyElementsHeader': typeof import("../components/elements/Header.vue")['default']
    'LazyElementsLoading': typeof import("../components/elements/Loading.vue")['default']
    'LazyElementsModal': typeof import("../components/elements/Modal.vue")['default']
    'LazyElementsNavDashboard': typeof import("../components/elements/NavDashboard.vue")['default']
    'LazyElementsSteps': typeof import("../components/elements/Steps.vue")['default']
    'LazyElementsWhatsApp': typeof import("../components/elements/WhatsApp.vue")['default']
    'LazyFieldButton': typeof import("../components/field/Button.vue")['default']
    'LazyFieldInput': typeof import("../components/field/Input.vue")['default']
    'LazyFieldSelect': typeof import("../components/field/Select.vue")['default']
    'LazyFieldSocialButton': typeof import("../components/field/SocialButton.vue")['default']
    'LazyFormsAuth': typeof import("../components/forms/Auth.vue")['default']
    'LazyFormsNewPassword': typeof import("../components/forms/NewPassword.vue")['default']
    'LazyFormsResetPassword': typeof import("../components/forms/ResetPassword.vue")['default']
    'LazyIconsClose': typeof import("../components/icons/Close.vue")['default']
    'LazyIconsHamburguer': typeof import("../components/icons/Hamburguer.vue")['default']
    'LazyIconsLoading': typeof import("../components/icons/Loading.vue")['default']
    'LazyIconsModal': typeof import("../components/icons/Modal.vue")['default']
    'LazyIconsSocialIcon': typeof import("../components/icons/SocialIcon.vue")['default']
    'LazyLogosBrand': typeof import("../components/logos/Brand.vue")['default']
    'LazySectionAdsReportsGoogle': typeof import("../components/section/AdsReports/Google.vue")['default']
    'LazySectionAdsReportsMeta': typeof import("../components/section/AdsReports/Meta.vue")['default']
    'LazySectionExpertises': typeof import("../components/section/Expertises.vue")['default']
    'LazySectionFormsBriefing': typeof import("../components/section/Forms/Briefing.vue")['default']
    'LazySectionFormsDados': typeof import("../components/section/Forms/Dados.vue")['default']
    'LazySectionHero': typeof import("../components/section/Hero.vue")['default']
    'LazySectionOurServicesAds': typeof import("../components/section/OurServices/Ads.vue")['default']
    'LazySectionOurServicesDesign': typeof import("../components/section/OurServices/Design.vue")['default']
    'LazySectionOurServicesSeo': typeof import("../components/section/OurServices/Seo.vue")['default']
    'LazySectionOurServicesSites': typeof import("../components/section/OurServices/Sites.vue")['default']
    'LazySectionPrices': typeof import("../components/section/Prices.vue")['default']
    'LazySectionProblemCases': typeof import("../components/section/ProblemCases.vue")['default']
    'LazySectionPropostaFunil': typeof import("../components/section/Proposta/Funil.vue")['default']
    'LazySectionPropostaFunil01': typeof import("../components/section/Proposta/Funil01.vue")['default']
    'LazySectionPropostaQuemSomos': typeof import("../components/section/Proposta/QuemSomos.vue")['default']
    'LazySectionProposta': typeof import("../components/section/Proposta/index.vue")['default']
    'LazySectionServices': typeof import("../components/section/Services.vue")['default']
    'LazySectionWhoUs': typeof import("../components/section/WhoUs.vue")['default']
    'LazyContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'LazyContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'LazyContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'LazyContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'LazyContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'LazyContentRendererMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'LazyContentSlot': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'LazyDocumentDrivenEmpty': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'LazyDocumentDrivenNotFound': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'LazyMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'LazyProseCode': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
    'LazyProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'LazyProsePre': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'LazyProseA': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
    'LazyProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'LazyProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'LazyProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'LazyProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'LazyProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'LazyProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'LazyProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'LazyProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'LazyProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'LazyProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'LazyProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'LazyProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'LazyProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'LazyProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'LazyProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'LazyProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'LazyProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'LazyProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'LazyProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'LazyProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'LazyProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'LazyProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyMDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'LazyMDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'LazyMDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const WhatsAppChatHeader: typeof import("../components/WhatsApp/ChatHeader.vue")['default']
export const WhatsAppChatMessages: typeof import("../components/WhatsApp/ChatMessages.vue")['default']
export const WhatsAppContactCard: typeof import("../components/WhatsApp/ContactCard.vue")['default']
export const WhatsAppMessageInput: typeof import("../components/WhatsApp/MessageInput.vue")['default']
export const WhatsAppSidebar: typeof import("../components/WhatsApp/Sidebar.vue")['default']
export const EffectsCardHoverBorder: typeof import("../components/effects/CardHoverBorder.vue")['default']
export const EffectsCardHoverGlow: typeof import("../components/effects/CardHoverGlow.vue")['default']
export const EffectsNumberRotate: typeof import("../components/effects/NumberRotate.vue")['default']
export const EffectsScrollX: typeof import("../components/effects/ScrollX.vue")['default']
export const EffectsWriter: typeof import("../components/effects/Writer.vue")['default']
export const ElementsFooter: typeof import("../components/elements/Footer.vue")['default']
export const ElementsHeader: typeof import("../components/elements/Header.vue")['default']
export const ElementsLoading: typeof import("../components/elements/Loading.vue")['default']
export const ElementsModal: typeof import("../components/elements/Modal.vue")['default']
export const ElementsNavDashboard: typeof import("../components/elements/NavDashboard.vue")['default']
export const ElementsSteps: typeof import("../components/elements/Steps.vue")['default']
export const ElementsWhatsApp: typeof import("../components/elements/WhatsApp.vue")['default']
export const FieldButton: typeof import("../components/field/Button.vue")['default']
export const FieldInput: typeof import("../components/field/Input.vue")['default']
export const FieldSelect: typeof import("../components/field/Select.vue")['default']
export const FieldSocialButton: typeof import("../components/field/SocialButton.vue")['default']
export const FormsAuth: typeof import("../components/forms/Auth.vue")['default']
export const FormsNewPassword: typeof import("../components/forms/NewPassword.vue")['default']
export const FormsResetPassword: typeof import("../components/forms/ResetPassword.vue")['default']
export const IconsClose: typeof import("../components/icons/Close.vue")['default']
export const IconsHamburguer: typeof import("../components/icons/Hamburguer.vue")['default']
export const IconsLoading: typeof import("../components/icons/Loading.vue")['default']
export const IconsModal: typeof import("../components/icons/Modal.vue")['default']
export const IconsSocialIcon: typeof import("../components/icons/SocialIcon.vue")['default']
export const LogosBrand: typeof import("../components/logos/Brand.vue")['default']
export const SectionAdsReportsGoogle: typeof import("../components/section/AdsReports/Google.vue")['default']
export const SectionAdsReportsMeta: typeof import("../components/section/AdsReports/Meta.vue")['default']
export const SectionExpertises: typeof import("../components/section/Expertises.vue")['default']
export const SectionFormsBriefing: typeof import("../components/section/Forms/Briefing.vue")['default']
export const SectionFormsDados: typeof import("../components/section/Forms/Dados.vue")['default']
export const SectionHero: typeof import("../components/section/Hero.vue")['default']
export const SectionOurServicesAds: typeof import("../components/section/OurServices/Ads.vue")['default']
export const SectionOurServicesDesign: typeof import("../components/section/OurServices/Design.vue")['default']
export const SectionOurServicesSeo: typeof import("../components/section/OurServices/Seo.vue")['default']
export const SectionOurServicesSites: typeof import("../components/section/OurServices/Sites.vue")['default']
export const SectionPrices: typeof import("../components/section/Prices.vue")['default']
export const SectionProblemCases: typeof import("../components/section/ProblemCases.vue")['default']
export const SectionPropostaFunil: typeof import("../components/section/Proposta/Funil.vue")['default']
export const SectionPropostaFunil01: typeof import("../components/section/Proposta/Funil01.vue")['default']
export const SectionPropostaQuemSomos: typeof import("../components/section/Proposta/QuemSomos.vue")['default']
export const SectionProposta: typeof import("../components/section/Proposta/index.vue")['default']
export const SectionServices: typeof import("../components/section/Services.vue")['default']
export const SectionWhoUs: typeof import("../components/section/WhoUs.vue")['default']
export const ContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const ContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const ContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const ContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const ContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const ContentRendererMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const ContentSlot: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const DocumentDrivenEmpty: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const DocumentDrivenNotFound: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const Markdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const ProseCode: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const ProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const ProsePre: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const ProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const MDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyWhatsAppChatHeader: typeof import("../components/WhatsApp/ChatHeader.vue")['default']
export const LazyWhatsAppChatMessages: typeof import("../components/WhatsApp/ChatMessages.vue")['default']
export const LazyWhatsAppContactCard: typeof import("../components/WhatsApp/ContactCard.vue")['default']
export const LazyWhatsAppMessageInput: typeof import("../components/WhatsApp/MessageInput.vue")['default']
export const LazyWhatsAppSidebar: typeof import("../components/WhatsApp/Sidebar.vue")['default']
export const LazyEffectsCardHoverBorder: typeof import("../components/effects/CardHoverBorder.vue")['default']
export const LazyEffectsCardHoverGlow: typeof import("../components/effects/CardHoverGlow.vue")['default']
export const LazyEffectsNumberRotate: typeof import("../components/effects/NumberRotate.vue")['default']
export const LazyEffectsScrollX: typeof import("../components/effects/ScrollX.vue")['default']
export const LazyEffectsWriter: typeof import("../components/effects/Writer.vue")['default']
export const LazyElementsFooter: typeof import("../components/elements/Footer.vue")['default']
export const LazyElementsHeader: typeof import("../components/elements/Header.vue")['default']
export const LazyElementsLoading: typeof import("../components/elements/Loading.vue")['default']
export const LazyElementsModal: typeof import("../components/elements/Modal.vue")['default']
export const LazyElementsNavDashboard: typeof import("../components/elements/NavDashboard.vue")['default']
export const LazyElementsSteps: typeof import("../components/elements/Steps.vue")['default']
export const LazyElementsWhatsApp: typeof import("../components/elements/WhatsApp.vue")['default']
export const LazyFieldButton: typeof import("../components/field/Button.vue")['default']
export const LazyFieldInput: typeof import("../components/field/Input.vue")['default']
export const LazyFieldSelect: typeof import("../components/field/Select.vue")['default']
export const LazyFieldSocialButton: typeof import("../components/field/SocialButton.vue")['default']
export const LazyFormsAuth: typeof import("../components/forms/Auth.vue")['default']
export const LazyFormsNewPassword: typeof import("../components/forms/NewPassword.vue")['default']
export const LazyFormsResetPassword: typeof import("../components/forms/ResetPassword.vue")['default']
export const LazyIconsClose: typeof import("../components/icons/Close.vue")['default']
export const LazyIconsHamburguer: typeof import("../components/icons/Hamburguer.vue")['default']
export const LazyIconsLoading: typeof import("../components/icons/Loading.vue")['default']
export const LazyIconsModal: typeof import("../components/icons/Modal.vue")['default']
export const LazyIconsSocialIcon: typeof import("../components/icons/SocialIcon.vue")['default']
export const LazyLogosBrand: typeof import("../components/logos/Brand.vue")['default']
export const LazySectionAdsReportsGoogle: typeof import("../components/section/AdsReports/Google.vue")['default']
export const LazySectionAdsReportsMeta: typeof import("../components/section/AdsReports/Meta.vue")['default']
export const LazySectionExpertises: typeof import("../components/section/Expertises.vue")['default']
export const LazySectionFormsBriefing: typeof import("../components/section/Forms/Briefing.vue")['default']
export const LazySectionFormsDados: typeof import("../components/section/Forms/Dados.vue")['default']
export const LazySectionHero: typeof import("../components/section/Hero.vue")['default']
export const LazySectionOurServicesAds: typeof import("../components/section/OurServices/Ads.vue")['default']
export const LazySectionOurServicesDesign: typeof import("../components/section/OurServices/Design.vue")['default']
export const LazySectionOurServicesSeo: typeof import("../components/section/OurServices/Seo.vue")['default']
export const LazySectionOurServicesSites: typeof import("../components/section/OurServices/Sites.vue")['default']
export const LazySectionPrices: typeof import("../components/section/Prices.vue")['default']
export const LazySectionProblemCases: typeof import("../components/section/ProblemCases.vue")['default']
export const LazySectionPropostaFunil: typeof import("../components/section/Proposta/Funil.vue")['default']
export const LazySectionPropostaFunil01: typeof import("../components/section/Proposta/Funil01.vue")['default']
export const LazySectionPropostaQuemSomos: typeof import("../components/section/Proposta/QuemSomos.vue")['default']
export const LazySectionProposta: typeof import("../components/section/Proposta/index.vue")['default']
export const LazySectionServices: typeof import("../components/section/Services.vue")['default']
export const LazySectionWhoUs: typeof import("../components/section/WhoUs.vue")['default']
export const LazyContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const LazyContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const LazyContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const LazyContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const LazyContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const LazyContentRendererMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const LazyContentSlot: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const LazyDocumentDrivenEmpty: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const LazyDocumentDrivenNotFound: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const LazyMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const LazyProseCode: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const LazyProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const LazyProsePre: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const LazyProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const LazyProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const LazyProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const LazyProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const LazyProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const LazyProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const LazyProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const LazyProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const LazyProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const LazyProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const LazyProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const LazyProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const LazyProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const LazyProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const LazyProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const LazyProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const LazyProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const LazyProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const LazyProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const LazyProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const LazyProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const LazyProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const LazyProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyMDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const LazyMDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const LazyMDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
