// Generated by nuxi
/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="@pinia/nuxt" />
/// <reference types="@nuxt/icon" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="@nuxt/content" />

export {}
