// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 08/08/2025, 14:48:02
const configMerger = require("C:/Users/TechSkillHub/Projetos/tsh.principalSite/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/TechSkillHub/Projetos/tsh.principalSite/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/plugins/**/*.{js,ts,mjs}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/composables/**/*.{js,ts,mjs}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/utils/**/*.{js,ts,mjs}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TechSkillHub/Projetos/tsh.principalSite/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["16"] = "C:/Users/TechSkillHub/Projetos/tsh.principalSite/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
