name: Deploy Nuxt via FTP

on:
  push:
    branches:
      - master # Substitua pelo nome da branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Altere para a versão necessária do Node.js
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.5.0
      with:
        server: ftp://<SEU-ENDERECO-FTP>
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: . # Substitua pelo diretório de saída do Nuxt
        server-dir: /root/projects/newSite
